PhilsNewFile.txt
You need this in your life. :)
=> Phil's file

PaperAnja.txt
This is my paper for your collection
=> Added my very own paper

paper_ejp.txt
=> Add paper_ejp.txt

andrew-file.txt, andy_paper.txt
I think this is the right place... ?  :-)
=> Edit an appropriate file and add my paper file

greatchange.txt
=> Specify great changes

pen.txt
Adds a simple text file called pen.txt
By looking at the above file.
Nah, not really.
Nope/
=> Added pen.txt

notfunnyjoke.txt
IT might make to chuckle but more likely not...
On line 1
Nope.
Your mood
=> Something not very funny added.

pen.txt
- Please read this template, and fill out the sections below with information about your pull request.
- PLEASE DELETE THIS INTRODUCTION SECTION BEFORE SUBMITTING YOUR PULL REQUEST!
Fix #[issue].
=> Just said thanks.

notfunnyjoke.txt
Just laughed at the non funny joke.
Yes, it is slightly funny.
=> Laghed a bit.

journal9.md
It adds my paper
at the beginning
I know what you did last Friday
It adds another paper
=> added my "paper"

Forking.txt
Adds my file
No fixes, just unnecessary files.
=> Forking directories is the best

PaperAnja.txt
=> Add 'Work hard on your paper'

PaperAnja.txt
I added a conclusion to PaperAnja.txt file.
=> Write conclusion to Anja's paper

noForksPaper.txt
Adds several interesting paragraphs from multiple random web pages relating to aerosols in Africa. "Clearly, no plagiarism here" said the student of the month 
Normally at the top
Not really, I didn't read most of it
I think it creates more...
=> Added my paper, noForksPaper.txt, TurnItIn will probably be 90%

richh.md
Adds a short review of the course in the style of a brief paper
=> Write brief overview of Git course for exercise

greatjoke.txt
Add a joke in file.
Fix #[issue].
=> A really good joke :)

Forking.md
=> Add real end

pullTest.txt
Add file to the main branch.
Master branch
No
No
=> Pull request test

journal.md
=> Pete's edit

cooke001_paper.txt
=> Add cooke001_paper.txt

newfile.txt
It adds a nifty new file "newfile.txt"
It's only one line of code
Nope
Thanks for helping me learn how to submit pull request!
=> A new file for a pull request test

very_important_research.md
=> added very important research journal

Toddler_strength_index.txt
=> Creation of the Toddler Strength Index Paper

interesting_paper.md
It adds my interesting paper to the collection.
=> added my interesting paper to your collection

paper_CPB.md
=> Copy Cristina's paper from the course.

Forking.md
Fix of incorrect formatting
Fix #97.
=> Fix Forking.md formatting (#97)

joke.txt
=> Added two more Joke :)

notesAboutGithub.txt
It's a chatGPT generated piece of text about git.
Check out the commands
No
No
=> Added notes about git

best_joke.txt
=> funny joke

worst_joke.txt
Added the worst joke I could find in ~5 secs
=> Add worst joke

paper_roger.md
=> Added paper from Roger

Maria_paper.md
Thank you very much for the training. Here is my pull request.
=> Add painting paper

thebestjoke.txt
This is the first joke I ever learned. Taught to me by my funny uncle. 
It is the best joke ever
=> The first joke I ever learned

airplane_joke.md
=> New airplane joke

jootd.txt
=> Add joke of the day

testy_mc_test_face.txt
=> Added testy mc test

next_day_questions.md
Add a markdown file for people who couldn't think of anything funny on the day to submit as a pull request, got back to it later to finish the assignment, and figure they have non-joke questions they might have asked Gerard.
The contents might be useful to them, to formulate questions, to Gerard, to offer topics to bring up if his next batch of students can't come up with their own questions, or to the next batch of students themselves at the end of their course.
Check out next_day_questions.md
No
No
=> Questions you came up with after the course is over

Patrick.txt
Added an important tip fresh from the Photon Science Institute
=> Added Patricks Joke
